# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Scan
  displayName: Scan sources
  jobs:
  - job: Scan
    displayName: Scan
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: docker pull quay.io/appthreat/sast-scan
      displayName: "Download sast-scan"
    - script: |
        docker run \
          -v "$(Build.SourcesDirectory):/app:cached" \
          -v "$(Build.ArtifactStagingDirectory):/reports:cached" \
          quay.io/appthreat/sast-scan scan --src /app \
          --out_dir /reports/CodeAnalysisLogs
      displayName: "AppThreat SAST and Dep scan"
      continueOnError: "true"
    - task: PublishBuildArtifacts@1
      displayName: "Publish analysis logs"
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)/CodeAnalysisLogs"
        ArtifactName: "CodeAnalysisLogs"
        publishLocation: "Container"
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)
